In [66]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder, MinMaxScaler, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.datasets import load_digits

In [77]:
df = pd.read_csv('pokemon.csv')

In [78]:
df = df.drop(columns=['name'])

In [79]:
X = df.drop(columns=['type'])
y = df['type']

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [81]:
sc = StandardScaler()
X_train_norm = pd.DataFrame(sc.fit_transform(X_train),columns=X_train.columns)
X_test_norm = pd.DataFrame(sc.transform(X_test),columns=X_train.columns)

In [86]:
lda = LinearDiscriminantAnalysis(n_components=5)
X_train_norm_lda = lda.fit_transform(X_train_norm, y_train)
X_test_norm_lda = lda.transform(X_test_norm)

In [93]:
lda.coef_[5]

array([ 1.81375497, -0.93282787,  0.08933357, -0.17734392, -1.36283033,
        0.54635647,  0.1958486 ])

In [94]:
X_train.columns

Index(['attack', 'defense', 'capture_rate', 'hp', 'sp_attack', 'sp_defense',
       'speed'],
      dtype='object')

In [95]:
lda.coef_[0]

array([ 0.00780646,  0.18828259,  0.09569408, -0.32456738, -0.45408829,
       -0.02263269,  0.16634165])

In [92]:
lda.classes_.tolist()

['bug',
 'dark',
 'dragon',
 'electric',
 'fairy',
 'fighting',
 'fire',
 'flying',
 'ghost',
 'grass',
 'ground',
 'ice',
 'normal',
 'poison',
 'psychic',
 'rock',
 'steel',
 'water']

In [35]:
dataset = load_digits()
X = pd.DataFrame(dataset['data'],columns=dataset['feature_names'])
y = dataset['target']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [36]:
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [37]:
lda = LinearDiscriminantAnalysis(n_components=9)
X_train_sc_lda = lda.fit_transform(X_train_sc, y_train)
X_test_sc_lda = lda.transform(X_test_sc)

In [38]:
X_train_sc_lda.shape

(1437, 9)

In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(X_train_sc_lda,y_train)
y_pred = rf.predict(X_test_sc_lda)
accuracy_score(y_test,y_pred)

0.9555555555555556

In [48]:
y_test = pd.DataFrame(y_test)
y_pred = pd.DataFrame(y_pred)

((y_test == 6) & (y_pred == 6)).sum() / (y_test == 6).sum()

0    1.0
dtype: float64

In [56]:
(y_test == 6).sum()

0    37
dtype: int64

In [57]:
(y_pred == 6).sum()

0    38
dtype: int64

In [61]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [62]:
cm

array([[41,  0,  0,  0,  2,  0,  0,  0,  0,  0],
       [ 0, 34,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0, 36,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 39,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0, 38,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0, 28,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 37,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 34,  1,  1],
       [ 0,  0,  0,  0,  0,  1,  1,  0, 24,  3],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1, 33]])

In [65]:
39/40

0.975